spring:
  profiles:
    active: development
  # Database

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:TEST
    driver-class-name: org.h2.Driver
    username: username
    password: password
    hikari:
      idle-timeout: 10000

  #  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/springpostgresdb?createDatabaseIfNotExist=true
#    username: postgres
#    password: password
  # JPA properties
  jpa:
    generate-ddl=true:
    hibernate:
      ddl-auto: create-drop  #When we use Liquidbase/Flyway it defaults to create-drop, in all other cases it defaults to none.
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: false