spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springpostgresdb?createDatabaseIfNotExist=true
    username: postgres
    password: password
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update  #When we use Liquidbase/Flyway it defaults to create-drop, in all other cases it defaults to none.
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false